services:

  rat:
    image: alaerof/rat-header:latest
    networks:
      - development
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5005:5005"
    environment:
      # JVM config
      - JAVA_OPTIONS=-XX:+UseG1GC -XX:MaxRAMPercentage=75
      - JAVA_DEBUG_ENABLE=true
      - JAVA_DEBUG_PORT=5005
      - APP_CALLBACK_URL=http://localhost:8080/callback

networks:
  development:
    driver: bridge
